plugins { id 'com.android.application' }

android {
    namespace 'com.example.sshtunnel'
    compileSdk 35
    buildFeatures { buildConfig true }

    defaultConfig {
        applicationId 'com.example.sshtunnel'
        minSdk 26
        targetSdk 35
        versionCode 30
        versionName '1.26-beta.4'
    }
}

dependencies {
    implementation 'com.github.mwiede:jsch:0.2.21'
}
